import json
U=json.load(open('qr/qr.json'))['uris']
def s(kick,title,body,cls=''):
    return f'<section class="slide {cls}"><div class="kick">{kick}</div><h1>{title}</h1>{body}</section>'
def qr(k,label,size=260): return f'<figure class="q" style="width:{size}px"><img src="{U[k]}"><figcaption>{label}</figcaption></figure>'
SOUL="## 지식 저장소 (Obsidian)\n- Vault 경로: /Users/[me]/Obsidian/vault\n- 아이디어·링크·결정은 vault에 저장, [[wikilink]] 연결\n- 프로젝트 질문은 답 전에 vault 먼저 검색\n- 저장하면 경로 + 한 줄 요약만 답한다"
S=[]
S.append('<section class="slide cover"><div class="kick">AI Agent Operator · 3시간 핸즈온</div><h1>내 폰에서 명령하는<br>AI 에이전트 세팅</h1><p class="sub">코드를 모르는 사람이 규칙을 정하고, 에이전트에게 시장을 읽히고, 모의 주문을 시키고, 결과를 검증하는 운영 루프를 한 바퀴 돕니다.</p><p class="tag">Hermes Agent · Dgrid · Telegram · LBank(읽기·모의 주문만) · Obsidian</p></section>')
S.append(s('완료 조건','오늘 끝나면 화면에 남는 것 5개','<ol class="big"><li>텔레그램에서 한 줄 보내면 <b>답이 온다</b></li><li>에이전트가 거래소 API로 <b>내 잔고와 BTC 1시간봉</b>을 읽어 보고한다</li><li>내가 종이에 쓴 <b>규칙 카드</b>대로 <b>모의 주문 1건</b>을 넣고 주문 ID를 보고한다</li><li>그 주문을 <b>취소</b>하고 취소를 확인한다</li><li>결과가 내 <b>Obsidian 노트 한 장</b>에 남는다</li></ol><p class="note">실돈 체결 0건. 출금 권한 0개. 이 둘이 깨지면 세션 실패.</p>'))
S.append(s('왜 에이전트로 트레이딩을 하나','영수증 하나','<div class="cols"><div><div class="num">$10.3M</div><div class="lab">거래 볼륨</div></div><div><div class="num">22,936</div><div class="lab">트레이드</div></div><div><div class="num">$100</div><div class="lab">시작 자본</div></div><div><div class="num">1위</div><div class="lab">ClawHacks Mantle Giga Claw</div></div></div><p class="note">2026년 4월, 15일. 처음부터 볼륨 봇이 아니었습니다. 8단계 계획 → 자본이 잠김 → 볼륨 트랙으로 수렴 → 작은 거래 루프를 살려 두고 버그를 잡고 가스·모델 비용을 관리해 끝까지 지켰습니다.</p><p class="pt">비개발자가 이긴 이유는 코드가 아니라 <b>규칙 · 기록 · 손절</b>이었습니다.</p>'))
S.append(s('Hermes가 뭐냐','텔레그램 한 줄에 일하는 비서','<ul class="big"><li>내 컴퓨터에서 돌아가고, 폰 텔레그램에서 명령합니다</li><li>파일을 읽고 쓰고, 웹을 보고, 명령을 실행하고, 정해진 시간에 반복합니다</li><li>OpenClaw는 웹을 클릭하는 <b>손</b>, Hermes는 일을 나누고 시키는 <b>비서</b>. 경쟁이 아니라 분업</li></ul><p class="note">오늘 필요한 부품은 셋. <b>컴퓨터 · 텔레그램 · 모델 키</b>. 모델 키는 Dgrid 무료 라우터를 쓰니 오늘 비용은 0입니다.</p>'))
S.append(f'<section class="slide center"><div class="kick">참가자 페이지</div><h1>이 QR 하나로 오늘 전부</h1>{qr("page","mainn6.github.io/hermes-session",360)}<p class="note">여섯 단계, 복사 버튼, 막힐 때 표. 키와 토큰은 채팅방에 올리지 않습니다.</p></section>')
S.append(s('STEP 01','Hermes 설치',f'<div class="two"><div><p>Apple Silicon 맥 또는 Windows 11. 인텔 맥은 미지원.</p><p>가장 쉬운 길은 데스크톱 설치 파일. 막히면 터미널 한 줄.</p><pre>curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash</pre><pre>hermes --version</pre></div>{qr("hermes","hermes-agent.nousresearch.com")}</div>'))
S.append(s('STEP 02','Dgrid에서 모델 키',f'<div class="two"><div><ol><li>dgrid.ai/api-keys → Sign in → <b>지갑 연결</b></li><li>Dashboard → Keys → <b>Create New Key</b></li><li>이름 <code>hermes-session</code> · 한도 5</li><li>키는 <b>한 번만</b> 보입니다 → 메모장</li></ol><p class="note">지갑 없는 분은 손 들어 주세요. 세션용 키를 드립니다.<br>오늘 모델은 <code>dgridai/free</code>. 크레딧 없이 됩니다.</p></div>{qr("dgrid","dgrid.ai/api-keys")}</div>'))
S.append(s('STEP 03','Hermes에 Dgrid 연결','<pre>hermes model   →  Custom endpoint</pre><table class="kv"><tr><td>API base URL</td><td><code>https://api.dgrid.ai/v1</code></td></tr><tr><td>API key</td><td>STEP 02 키</td></tr><tr><td>Model name</td><td><code>dgridai/free</code></td></tr></table><pre>hermes -z "한 줄로 인사해줘"</pre><p class="note">답이 오면 통과. 이상하면 base URL 오타부터.</p>'))
S.append(s('STEP 04','텔레그램 봇 연결',f'<div class="two"><div><ol><li>@BotFather → <code>/newbot</code> → <b>토큰</b></li><li>@userinfobot → 내 <b>ID 숫자</b></li><li><code>hermes gateway setup</code> → Telegram → 토큰·ID</li><li><code>hermes gateway</code> 켜 두고 폰에서 <b>“안녕”</b></li></ol><p class="note">답이 오면 완료 조건 1 통과.</p></div><div class="qrow">{qr("botfather","@BotFather",200)}{qr("userinfo","@userinfobot",200)}</div></div>'))
S.append(s('STEP 05','완료 체크','<pre>curl -fsSL https://mainn6.github.io/hermes-session/check.sh -o check.sh && bash check.sh</pre><ul class="big"><li>설치 · 모델(custom → dgrid) · 키 유효 · 봇 토큰 · 허용 ID · 게이트웨이</li><li>비밀값은 출력하지 않습니다</li><li>FAIL 줄만 사진으로 보내 주세요</li></ul>'))
S.append(s('규칙 카드','종이 한 장, 일곱 칸','<div class="grid7"><div>종목 1개</div><div>진입 조건 1개</div><div>손절 %</div><div>익절 %</div><div>1회 주문 한도 (숫자)</div><div>거래 금지 시간·조건</div><div>하루 최대 손실</div></div><p class="note">이 카드가 그대로 에이전트의 역할 카드(시스템 프롬프트)가 됩니다. “이 한도를 넘는 주문은 거절하고 사람에게 묻는다”는 문장은 고정.</p>'))
S.append(s('안전 규칙','강사 화면에 상시','<ul class="big"><li>API 키는 <b>읽기 + 거래만</b>. 출금 권한 <b>절대 OFF</b>. IP 화이트리스트</li><li>모의 계정 또는 잔고 0 계정만. 실돈 계정 연결은 강사가 막습니다</li><li>1회 한도는 숫자로. 초과 주문은 거절 후 사람에게</li><li>서킷 브레이커: 가스 부족 → 정지 · 자본 하한 → 정지 · 연속 실패 20회 → halt</li><li>키·토큰이 화면에 비치지 않게. 입력은 설정 프롬프트로만</li></ul>'))
S.append(s('블록 5','먼 지정가 → 취소','<ol class="big"><li>“규칙대로 지금 판단해”</li><li>에이전트가 규칙 카드 확인 → 현재가 대비 <b>30% 아래 BUY 지정가 0.0001 BTC</b> (체결 불가)</li><li>주문 ID · 상태 4(대기) 보고</li><li>10초 대기 (거래 호출은 키당 10초 1회)</li><li>“취소해” → 주문 목록에서 사라진 것 확인</li></ol><p class="note">조건이 안 맞으면 <b>no-trade가 정답</b>입니다. 그것도 완료.</p>'))
S.append(s('업무에 붙이는 패턴 ①','텔레그램 방 = 업무 접수창 (예시 구성)','<table class="kv"><tr><td>업무보고방</td><td>완료·진행·이슈·계획 → Docs 상세 + 시트 요약</td></tr><tr><td>회의록방</td><td>메모·녹취·화이트보드 사진 → 회의록 Docs + 시트</td></tr><tr><td>일정방</td><td>“내일 3시 미팅” → 캘린더(+Meet)</td></tr><tr><td>명함방</td><td>명함 사진 → 연락처 시트</td></tr><tr><td>지출방</td><td>영수증 사진 → 경비 시트</td></tr><tr><td>General</td><td>“주간 업무보고” → 전체 종합 Docs</td></tr></table><p class="note">방마다 스킬 하나를 묶는 구성. 저장 직전 “맞나요?” 한 번. 사람이 마지막 확인.</p>'))
S.append(s('업무에 붙이는 패턴 ②','반복 작업 · 이미지와 영상','<div class="two"><div><h3>반복 작업(크론)</h3><p>예: 평일 아침 시장 지수와 수급을 웹에서 읽어 5줄 요약 → 텔레그램.</p><p class="note">만드는 방법은 대화 한 줄. “매일 9시에 … 보내줘. 반복 작업으로 등록해.”</p></div><div><h3>Higgsfield 스킬</h3><p>“이 레퍼런스 톤으로 디너 포스터” → GPT Image 2.5<br>“캐릭터가 돌아보는 3D 영상” → Seedance 2.5</p><p class="note">크레딧이 드는 작업. 시안은 480p, 채택분만 1080p.</p></div></div>'))
S.append(s('업무에 붙이는 패턴 ③','Obsidian 연결 3단계','<ol class="big"><li>볼트 폴더 만들기. 처음엔 <b>전용 폴더</b>만 개방</li><li><code>hermes skills list | grep -i obsidian</code> — 기본 스킬 확인</li><li><code>~/.hermes/SOUL.md</code>에 경로와 규칙 적기</li></ol><pre class="soul">'+SOUL+'</pre><p class="note">에이전트 메모리는 2,200자. 긴 기록은 볼트에. 사람도 같은 파일을 봅니다.</p>'))
S.append(s('원칙 셋','회사에서 써도 되는 조건','<ol class="big"><li>위험한 일은 실행 전에 <b>묻는다</b>. 메일 발송 · 결제 · 실거래 · 삭제</li><li>진실은 채팅이 아니라 <b>볼트</b>에 있다. 저장 안 된 결정은 없는 결정</li><li>키는 <b>파일에만</b>. 채팅 · 스크린샷 · 문서에 안 남긴다</li></ol>'))
S.append(f'<section class="slide center"><div class="kick">종료</div><h1>옆 사람 봇에 “잔고 알려줘”</h1><p class="sub">답이 오면 오늘 완료입니다. 집에 가서 실돈 계정에 연결하지 않습니다. 오늘 만든 키는 지워도 됩니다.</p>{qr("page","mainn6.github.io/hermes-session",240)}</section>')
CSS='''
:root{--bg:#070a0b;--ink:#eef4f6;--muted:#97a9b0;--acc:#97d3eb;--acc2:#ffd879;--line:#233036;--panel:#0f1517}
*{box-sizing:border-box;margin:0;padding:0}html,body{height:100%;background:var(--bg);color:var(--ink);font-family:"IBM Plex Sans KR",Pretendard,-apple-system,"Segoe UI",sans-serif}
body{overflow:hidden}.deck{position:relative;width:100vw;height:100vh}
.slide{position:absolute;inset:0;padding:7vh 8vw;display:none;flex-direction:column;justify-content:center;gap:2.2vh}.slide.on{display:flex}
.kick{color:var(--acc2);font-size:1.5vh;font-weight:800;letter-spacing:.16em;text-transform:uppercase}
h1{font-size:6.2vh;line-height:1.08;letter-spacing:-.03em}.cover h1{font-size:9vh}.center{align-items:center;text-align:center}
h3{font-size:3vh;color:var(--acc);margin-bottom:1vh}
p,li,td{font-size:2.6vh;line-height:1.5}.sub{color:var(--muted);font-size:3vh;max-width:70vw}.tag{color:var(--acc);font-size:2vh}
.note{color:var(--muted);font-size:2.2vh}.pt{font-size:3.2vh}
ol.big,ul.big{padding-left:3.2vh}ol.big li,ul.big li{font-size:3.1vh;margin:.9vh 0}
.cols{display:flex;gap:6vw;margin:2vh 0}.num{font-size:7.5vh;font-weight:800;letter-spacing:-.03em;color:var(--acc)}.lab{color:var(--muted);font-size:2vh}
.two{display:grid;grid-template-columns:1fr auto;gap:6vw;align-items:center}.qrow{display:flex;gap:3vw}
figure.q{text-align:center}figure.q img{width:100%;background:#fff;border-radius:1.6vh;padding:1vh}figcaption{color:var(--muted);font-size:1.8vh;margin-top:.8vh}
pre{background:var(--panel);border:1px solid var(--line);border-radius:1.4vh;padding:1.8vh 2.2vh;font:2.3vh/1.5 ui-monospace,Menlo,monospace;white-space:pre-wrap;overflow-wrap:anywhere;color:#e6f0f3;margin:1vh 0}
pre.soul{font-size:2vh}code{background:#16232a;padding:.2vh .8vh;border-radius:.8vh}
.kv{border-collapse:collapse;width:100%}.kv td{padding:1.2vh 1.4vh;border-bottom:1px solid var(--line);vertical-align:top}.kv td:first-child{color:var(--muted);width:24%}
.grid7{display:grid;grid-template-columns:repeat(4,1fr);gap:1.6vh;margin:1vh 0}.grid7 div{border:1px solid var(--line);border-radius:1.4vh;padding:2.4vh 1.8vh;font-size:2.6vh;background:var(--panel)}
.pager{position:fixed;right:2vw;bottom:2vh;color:var(--muted);font-size:1.6vh}
@media print{@page{size:338.7mm 190.5mm;margin:0}body{overflow:visible}.deck{height:auto}.slide{display:flex!important;position:relative;height:190.5mm;width:338.7mm;page-break-after:always;padding:14mm 26mm}.pager{display:none}
h1{font-size:34pt}.cover h1{font-size:48pt}p,li,td{font-size:14pt}ol.big li,ul.big li{font-size:17pt}.sub{font-size:16pt}.kick{font-size:9pt}.note{font-size:12pt}.num{font-size:40pt}.lab{font-size:11pt}pre{font-size:13pt}pre.soul{font-size:11pt}figcaption{font-size:10pt}.grid7 div{font-size:14pt}.pt{font-size:17pt}h3{font-size:16pt}.tag{font-size:11pt}figure.q{width:60mm!important}}
'''
JS='''const sl=[...document.querySelectorAll('.slide')];let i=Math.max(0,Math.min(sl.length-1,parseInt(location.hash.slice(1)||'0')));function go(n){i=(n+sl.length)%sl.length;sl.forEach((s,k)=>s.classList.toggle('on',k===i));location.hash=i;document.getElementById('pg').textContent=(i+1)+' / '+sl.length}
addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key))go(i+1);if(['ArrowLeft','PageUp'].includes(e.key))go(i-1);if(e.key==='Home')go(0)});addEventListener('click',e=>{if(e.clientX>innerWidth/2)go(i+1);else go(i-1)});go(i)'''
html='<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hermes 세션 덱</title><style>'+CSS+'</style></head><body><div class="deck">'+''.join(S)+'</div><div class="pager" id="pg"></div><script>'+JS+'</script></body></html>'
open('deck.html','w',encoding='utf-8').write(html); print('deck slides',len(S))
